"""update total price of th order

Revision ID: 02e583c2bee4
Revises: 3bb397c76d94
Create Date: 2026-02-09 23:16:59.024266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e583c2bee4'
down_revision: Union[str, Sequence[str], None] = '3bb397c76d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('subtotal', sa.Float(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('tax', sa.Float(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('delivery', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery')
    op.drop_column('orders', 'tax')
    op.drop_column('orders', 'subtotal')
    # ### end Alembic commands ###
