"""update createdAt

Revision ID: 05c8dee3338f
Revises: afb3571c778d
Create Date: 2026-03-02 15:02:05.311175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05c8dee3338f'
down_revision: Union[str, Sequence[str], None] = 'afb3571c778d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('ADMIN', 'STAFF', 'CUSTOMER', name='userrole'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
