"""update user for token

Revision ID: 3451d7eba30b
Revises: fc3ae503a0fe
Create Date: 2026-03-01 22:14:19.514181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3451d7eba30b'
down_revision: Union[str, Sequence[str], None] = 'fc3ae503a0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('userID', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('refresh_tokens_staffID_fkey'), 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(op.f('refresh_tokens_customerID_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['userID'], ['id'], ondelete='CASCADE')
    op.drop_column('refresh_tokens', 'staffID')
    op.drop_column('refresh_tokens', 'customerID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('customerID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('refresh_tokens', sa.Column('staffID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_customerID_fkey'), 'refresh_tokens', 'users', ['customerID'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('refresh_tokens_staffID_fkey'), 'refresh_tokens', 'users', ['staffID'], ['id'], ondelete='CASCADE')
    op.drop_column('refresh_tokens', 'userID')
    # ### end Alembic commands ###
