"""initial_migration

Revision ID: 3bb397c76d94
Revises: 
Create Date: 2026-01-28 18:51:25.456541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb397c76d94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phoneNumber', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_phoneNumber'), 'customer', ['phoneNumber'], unique=True)
    op.create_table('discount',
    sa.Column('category', sa.Enum('ORDER', 'DISH', 'CUSTOMER', name='discountcategory'), nullable=True),
    sa.Column('dateBegin', sa.DateTime(), nullable=False),
    sa.Column('dateEnd', sa.DateTime(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tables',
    sa.Column('status', sa.Enum('Empty', 'Booked', 'Deleted', 'Taken', name='tablestatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dish',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Double(), nullable=False),
    sa.Column('imgUrl', sa.String(length=255), nullable=False),
    sa.Column('describe', sa.Text(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('categoryID', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['categoryID'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phoneNumber', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('roleID', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['roleID'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('dateOrder', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OUT_FOR_DELIVERY', 'DELIVERY_SUCCESSFUL', 'CANCELLED', 'PENDING_PAYMENT', name='orderstatus'), nullable=False),
    sa.Column('totalPrice', sa.Double(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('staffID', sa.Integer(), nullable=False),
    sa.Column('customerID', sa.Integer(), nullable=False),
    sa.Column('tableID', sa.Integer(), nullable=False),
    sa.Column('discountID', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['customerID'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['discountID'], ['discount.id'], ),
    sa.ForeignKeyConstraint(['staffID'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['tableID'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_dateOrder'), 'orders', ['dateOrder'], unique=False)
    op.create_table('reviews',
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('customerID', sa.Integer(), nullable=False),
    sa.Column('dishID', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['customerID'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['dishID'], ['dish.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_detail',
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Double(), nullable=False),
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.Column('dishID', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['dishID'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['orderID'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_detail')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_orders_dateOrder'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('staff')
    op.drop_table('dish')
    op.drop_table('tables')
    op.drop_table('roles')
    op.drop_table('discount')
    op.drop_index(op.f('ix_customer_phoneNumber'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('categories')
    # ### end Alembic commands ###
