"""add_server_defaults_for_user_and_discount_status

Revision ID: 78bb1a25f83d
Revises: 99fca9a88634
Create Date: 2026-03-02 15:40:29.346317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78bb1a25f83d'
down_revision: Union[str, Sequence[str], None] = '99fca9a88634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
