"""add updatedAt, rename createdAt

Revision ID: 99fca9a88634
Revises: 2d7aa05ef94c
Create Date: 2026-03-02 15:34:53.919693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99fca9a88634'
down_revision: Union[str, Sequence[str], None] = '2d7aa05ef94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_categories_updated_at'), 'categories', ['updated_at'], unique=False)
    op.add_column('discount', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_discount_updated_at'), 'discount', ['updated_at'], unique=False)
    op.add_column('dish', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_dish_updated_at'), 'dish', ['updated_at'], unique=False)
    op.add_column('order_details', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_order_details_updated_at'), 'order_details', ['updated_at'], unique=False)
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_orders_updated_at'), 'orders', ['updated_at'], unique=False)
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_refresh_tokens_updated_at'), 'refresh_tokens', ['updated_at'], unique=False)
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_reviews_updated_at'), 'reviews', ['updated_at'], unique=False)
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_roles_updated_at'), 'roles', ['updated_at'], unique=False)
    op.add_column('tables', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_tables_updated_at'), 'tables', ['updated_at'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_index(op.f('ix_tables_updated_at'), table_name='tables')
    op.drop_column('tables', 'updated_at')
    op.drop_index(op.f('ix_roles_updated_at'), table_name='roles')
    op.drop_column('roles', 'updated_at')
    op.drop_index(op.f('ix_reviews_updated_at'), table_name='reviews')
    op.drop_column('reviews', 'updated_at')
    op.drop_index(op.f('ix_refresh_tokens_updated_at'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'updated_at')
    op.drop_index(op.f('ix_orders_updated_at'), table_name='orders')
    op.drop_column('orders', 'updated_at')
    op.drop_index(op.f('ix_order_details_updated_at'), table_name='order_details')
    op.drop_column('order_details', 'updated_at')
    op.drop_index(op.f('ix_dish_updated_at'), table_name='dish')
    op.drop_column('dish', 'updated_at')
    op.drop_index(op.f('ix_discount_updated_at'), table_name='discount')
    op.drop_column('discount', 'updated_at')
    op.drop_index(op.f('ix_categories_updated_at'), table_name='categories')
    op.drop_column('categories', 'updated_at')
    # ### end Alembic commands ###
