"""update tableID allow null

Revision ID: 9f453cf969b2
Revises: 02e583c2bee4
Create Date: 2026-02-10 00:29:48.204560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f453cf969b2'
down_revision: Union[str, Sequence[str], None] = '02e583c2bee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'tableID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'tableID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
