"""add expire_at of token

Revision ID: afb3571c778d
Revises: 7d73d10da7e3
Create Date: 2026-03-01 22:27:10.019389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb3571c778d'
down_revision: Union[str, Sequence[str], None] = '7d73d10da7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('expiresAt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'expiresAt')
    # ### end Alembic commands ###
