"""init tables

Revision ID: fc3ae503a0fe
Revises: 
Create Date: 2026-03-01 22:05:11.713884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc3ae503a0fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_createdAt'), 'categories', ['createdAt'], unique=False)
    op.create_table('discount',
    sa.Column('category', sa.Enum('ORDER', 'DISH', 'CUSTOMER', name='discountcategory'), nullable=True),
    sa.Column('dateBegin', sa.DateTime(), nullable=False),
    sa.Column('dateEnd', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='status'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_createdAt'), 'discount', ['createdAt'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_createdAt'), 'roles', ['createdAt'], unique=False)
    op.create_table('tables',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('min_capacity', sa.Integer(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Empty', 'Booked', 'Deleted', 'Taken', name='tablestatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_capacity >= min_capacity', name='check_max_ge_min'),
    sa.CheckConstraint('min_capacity > 0', name='check_min_capacity_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_tables_createdAt'), 'tables', ['createdAt'], unique=False)
    op.create_table('dish',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('imgUrl', sa.String(length=255), nullable=False),
    sa.Column('describe', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='status'), nullable=False),
    sa.Column('categoryID', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['categoryID'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_createdAt'), 'dish', ['createdAt'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'CUSTOMER', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='status'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phoneNumber', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('roleID', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['roleID'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_createdAt'), 'users', ['createdAt'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phoneNumber'), 'users', ['phoneNumber'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('orders',
    sa.Column('status', sa.Enum('PENDING', 'OUT_FOR_DELIVERY', 'DELIVERY_SUCCESSFUL', 'CANCELLED', 'PENDING_PAYMENT', name='orderstatus'), nullable=False),
    sa.Column('totalPrice', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('delivery', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('staffID', sa.Integer(), nullable=False),
    sa.Column('customerID', sa.Integer(), nullable=False),
    sa.Column('tableID', sa.Integer(), nullable=True),
    sa.Column('discountID', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customerID'], ['users.id'], ),
    sa.ForeignKeyConstraint(['discountID'], ['discount.id'], ),
    sa.ForeignKeyConstraint(['staffID'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tableID'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_createdAt'), 'orders', ['createdAt'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('userAgent', sa.String(length=255), nullable=True),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('staffID', sa.Integer(), nullable=True),
    sa.Column('customerID', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customerID'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staffID'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_createdAt'), 'refresh_tokens', ['createdAt'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('reviews',
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('dishID', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dishID'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_createdAt'), 'reviews', ['createdAt'], unique=False)
    op.create_table('order_details',
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.Column('dishID', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dishID'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['orderID'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_details_createdAt'), 'order_details', ['createdAt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_details_createdAt'), table_name='order_details')
    op.drop_table('order_details')
    op.drop_index(op.f('ix_reviews_createdAt'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_createdAt'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_orders_createdAt'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phoneNumber'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_createdAt'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dish_createdAt'), table_name='dish')
    op.drop_table('dish')
    op.drop_index(op.f('ix_tables_createdAt'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_roles_createdAt'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_discount_createdAt'), table_name='discount')
    op.drop_table('discount')
    op.drop_index(op.f('ix_categories_createdAt'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
